# Generated by Django 5.0.7 on 2024-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "site_shop",
            "0005_alter_article_options_alter_feedbackmessage_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateTimeField(null=True, verbose_name="Дата написания"),
        ),
    ]
