# Generated by Django 5.0.7 on 2024-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_shop", "0006_article_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="date",
            field=models.DateField(null=True, verbose_name="Дата написания"),
        ),
    ]
